pattern_name: exposure_to_environmentalprocess_route
pattern_iri: http://purl.obolibrary.org/obo/ecto/patterns/exposure_to_environmentalprocess_route.yaml

description: "exposures to an environmental process where the route is known"

contributors:
  - https://orcid.org/0000-0002-2908-3327

classes:
  exposure event: ExO:0000002
  environmental process: ENVO:02500000
  route: ExO:0000055

annotationProperties:
  exact_synonym: oio:hasExactSynonym

relations:
  has exposure stimulus: RO:0002309
  has exposure route: RO:0002242
    
vars: 
  stressor: "'environmental process'"
  route: "'route'"

name:
  text: "exposure to %s in %s"
  vars:
    - stressor
    - route

annotations: 
  - annotationProperty: exact_synonym
    text: "%s exposure in %s"
    vars:
      - stressor
      - route

def: 
  text: "A exposure event involving the interaction of an exposure receptor to %s happening in %s of the receptor."
  vars:
    - stressor
    - route

equivalentTo: 
  text: "'exposure event' and ('has exposure stimulus' some %s) and ('has exposure route' some %s)"
  vars:
    - stressor
    - route
