pattern_name: exposure_to_environmental_system
pattern_iri: http://purl.obolibrary.org/obo/ecto/patterns/exposure_to_environmental_system.yaml

description: "exposures to an environmental system"

contributors:
  - https://orcid.org/0000-0002-2908-3327

classes:
  exposure event: ExO:0000002
  environmental system: ENVO:01000254

annotationProperties:
  exact_synonym: oio:hasExactSynonym

relations:
  has exposure stimulus: RO:0002309

vars:
  stressor: "'environmental system'"

name:
  text: "exposure to %s"
  vars:
    - stressor

annotations:
  - annotationProperty: exact_synonym
    text: "%s exposure"
    vars:
      - stressor

def: 
  text: "A exposure event involving the interaction of an exposure receptor to %s."
  vars:
    - stressor

equivalentTo: 
  text: "'exposure event' and ('has exposure stimulus' some %s)"
  vars:
    - stressor
